<?php

declare(strict_types=1);

/*
 * Keys read by Modules\Xot\Traits\EnumTrait through TransTrait::transClass():
 * `<module>::<snake(ClassName)>.values.<value>.<attribute>`.
 */

return [
    'values' => [
        'user' => [
            'label' => 'User',
            'color' => 'primary',
            'icon' => 'heroicon-o-user',
            'description' => 'Message written by the user',
        ],
        'assistant' => [
            'label' => 'Assistant',
            'color' => 'info',
            'icon' => 'heroicon-o-sparkles',
            'description' => 'Reply generated by the AI assistant',
        ],
        'tool' => [
            'label' => 'Tool',
            'color' => 'warning',
            'icon' => 'heroicon-o-wrench-screwdriver',
            'description' => 'Result of a tool call',
        ],
        'system' => [
            'label' => 'System',
            'color' => 'gray',
            'icon' => 'heroicon-o-cog-6-tooth',
            'description' => 'System instructions for the model',
        ],
    ],
];
